kafka:
  bootstrap-servers: 127.0.0.1:9091
  topic.request-topic: ProductRequest
  topic.requestreply-topic: ProductRequest
  consumergroup: requestreplygorup

spring:
  application:
    name: producer

  kafka:
    producer:
      max:
        request:
          size: 231072000
      batch-size: 60000000
      buffer-memory: 60000000
    bootstrap-servers: 127.0.0.1:9091
    client-id: producer
    consumer:
      group-id: requestreplygroup
      auto-offset-reset: earliest
      enable-auto-commit: false